### ISSUE TITLE
Can we make a new release?

### ISSUE THREAD

**Issue by peterberkenbosch** [solidusio/solidus_i18n#188]
Currently the released version still locks the ruby version to `Ruby (~> 2.4)`. Master branch has this solved, but it's preventing sandbox creation on Solidus master currently,

**Comment by Mateus-Resende** [comment]
I'm also facing the same issue, do we have a release planned anytime soon?

**Comment by ccarruitero** [comment]
ping @kennyadsl

**Comment by kennyadsl** [comment]
Done, thanks for pinging me!
