### ISSUE TITLE
Allow setting available locales for each store

### ISSUE THREAD

**Issue by tvdeyen** [solidusio/solidus_i18n#82]
Solidus 2.2 (latest `master` while creating this issue) [has dropped the general settings page](https://github.com/solidusio/solidus/pull/1282) in favour of settings for individual stores.

This gem only allows to set one global setting. We should add support for locales settings for each individual store as this is one of the general purposes of running multiple stores.

**Comment by jhawthorn** [comment]
As a temporary quick fix, I've done #83, but this would be an even better solution.

**Comment by softr8** [comment]
On it

**Comment by DanielePalombo** [comment]
I'm on it

**Comment by aitbw** [comment]
I think this is safe to close as per #95 and solidusio/solidus#2674
